media_gallery/models.py
import random

from django.db import models
from django.conf import settings

from pwd_this.models import Password



class Collection(models.Model):
    """
        A collection of galleries.
    """
    name = models.CharField(max_length=75)
    slug = models.SlugField(max_length=150, primary_key=True)
    created_on = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.name


class MediaGallery(models.Model):
    name = models.CharField(max_length=75)
    slug = models.SlugField(max_length=150, primary_key=True)
    # Neccessary for django-uploadit
    created_on = models.DateTimeField(auto_now_add=True)
    collection = models.ForeignKey(Collection, related_name='gallery_set')
    lock = models.BooleanField(default=False, verbose_name='login Required', 
        help_text="Prompts for a password when viewing this gallery.")
    password = models.OneToOneField(Password, related_name='media_gallery', editable=False, blank=True, null=True)
    published = models.BooleanField(default=False)

    @property
    def thumbnail(self):
        """
            Gets a random image from this gallery and returns its thumbnail.
        """
        try:
            return self._thumbnail
        except AttributeError:
            images = self.images.all()
            if bool(images):
                self._thumbnail = random.choice(images).thumbnail
                return self._thumbnail

    def get_picture_positions(self):
        """
            Returns a dictionary mapping an image's position with its id.
        """
        pictures = self.images.get_custom_sorted()
        positions = {}
        for pos, picture in enumerate(pictures):
            # 1 indexed
            positions[picture.id] = pos + 1
        return positions

    @models.permalink
    def get_absolute_url(self):
        return ('media-gallery', [self.collection.slug, self.slug])


    def __unicode__(self):
        return self.name


def calc_image_path(instance, name):
    return "%s/%s" % (instance.gallery.slug, name)


def calc_thumbnail_path(instance, name):
    return "%s/thumbnails/%s" % (instance.gallery.slug, name)


class UploadedImage(models.Model):
    """
        Extends the UploadedFile object.
        Adds a relationship to MediaGallery.
    """
    image = models.ImageField(max_length=250, upload_to=calc_image_path)
    thumbnail = models.ImageField(max_length=250, upload_to=calc_thumbnail_path)
    gallery = models.ForeignKey(MediaGallery, related_name='images')
    upload_date = models.DateTimeField(auto_now_add=True)


    def __unicode__(self):
        return self.image.name

    class Meta:
        # Defined as abstract because this is not meant to create a table.
        # But to extend the UploadedFile model which is in charge of creating its table.
        abstract = True

media_gallery/templates/media-gallery/add.html
{% extends "media-gallery/base.html" %}

{% block title %}Create a Gallery{% endblock %}

{% block content %}
<form action="" class=".form-vertical" method="post">{% csrf_token %}
	<fieldset>
		{% for field in form.visible_fields %}
		<div class="control-group {% if field.errors %}error{% endif %}">
			{{ field.label_tag }}
			<div class="controls">
				{{ field }}
				{% if field.help_text %}
				<p class="help-block">{{ field.help_text }}</p>
				{% endif %}
			</div>
			{{ field.errors }}
		</div>
		{% endfor %}
  </fieldset>
   	{% for hidden in form.hidden_fields %}
    {{ hidden }}
    {% endfor %}
    <input type="submit" class="btn btn-large btn-primary" value="Create" />
</form>
{% endblock %}
{% block js %}
<script type="text/javascript" src="{{ STATIC_URL }}jQuery-Slugify-Plugin/jquery.slugify.js"></script>
<script type="text/javascript">
	$('#id_slug').slugify('#id_name');
</script>
{% endblock js %}

media_gallery/templates/media-gallery/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap CSS Toolkit styles -->
    <link rel="stylesheet" href="{{ STATIC_URL }}bootstrap/css/bootstrap.min.css">
    <!-- Bootstrap styles for responsive website layout, supporting different screen sizes -->
    <link rel="stylesheet" href="{{ STATIC_URL }}bootstrap/css/bootstrap-responsive.min.css">
    {% block extra-style %}{% endblock extra-style %}
    {% block extra-head %}{% endblock extra-head %}
</head>
<body>
    <div class="container">
        <ul class="breadcrumb">
            <li>
                <a href="{% url "gallery-dashboard" %}">Dashboard</a>
            </li>
        </ul>
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            <button class="close" data-dismiss="alert">×</button>
            {{ message }}
        </div>
        {% endfor %}
        {% endif %}
        {% block content %}
        {% endblock content %}
    </div>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js" type="text/javascript"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}bootstrap/js/bootstrap-alert.js" type="text/javascript"></script>
    <script type="text/javascript">
        $(".alert").alert()
    </script>
    {% block js %}{% endblock js %}
</body>
</html>

media_gallery/templates/media-gallery/dashboard.html
{% extends "media-gallery/base.html" %}

{% block extra-style %}
<link rel="stylesheet" href="{{ STATIC_URL }}Impromptu/css/default.css">
{% endblock extra-style %}

{% block title %}Dashboard{% endblock %}

{% block content %}
<ul class="thumbnails">
{% for gallery in galleries %}
    <li class=".span3">
    <div class="thumbnail">
        <a class="edit" href="{% url "gallery-edit" gallery.pk %}">
            <img src="{{ gallery.thumbnail.url }}" width="{{ gallery.thumbnail.width }}" height="{{ gallery.thumbnail.height }}" />
        </a>
        <h3 style="text-align: center;">{{ gallery.name }}</h3>
        <a title="Delete ?" rel="tooltip" class="delete" href="{% url "gallery-delete" gallery.pk %}"><i class="icon-trash"></i></a>
    </div>
    </li>
{% endfor %}
</ul>
{% endblock %}

{% block js %}
<script type="text/javascript" src="{{ STATIC_URL }}Impromptu/js/jquery-impromptu.4.0.min.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}bootstrap/js/bootstrap-tooltip.js"></script>
<script type="text/javascript">
    $(".thumbnail a.delete").click(function (event) {
        event.preventDefault();
        var atag = $(this);
        var link = atag.attr("href");
        $.prompt("Do you really want to delete this gallery ?", {
            buttons: { Yes: 1, No: 0 },
            submit:function(e,v,m,f){
                if(v===0){
                    $.prompt.close();
                }
                else if(v===1){
                    $.getJSON(link, function(data) {
                        if(data===0){
                            html = '<div class="alert alert-error"><button class="close" data-dismiss="alert">×</button>Oops something went wrong, gallery was not deleted.</div>'
                        }
                        else{
                                html = '<div class="alert alert-success"><button class="close" data-dismiss="alert">×</button>Your gallery has been deleted successfully.</div>'
                                atag.parent('div').parent('li').remove()
                            }
                        $(html).prependTo($('.container'));
                    });
                    return true;
                }
            }
        });
    });
</script>
{% endblock js %}

media_gallery/templates/media-gallery/edit.html
{% extends "media-gallery/base.html" %}

{% block extra-style %}
<link rel="stylesheet" href="{{ STATIC_URL }}Impromptu/css/default.css">
<link rel="stylesheet" href="{{ STATIC_URL }}iphone-style-checkboxes/css/style.css">
{% endblock extra-style %}

{% block title %}Edit a Gallery{% endblock %}

{% block content %}
<form action="" class=".form-vertical" method="post">{% csrf_token %}
    <fieldset>
        {% for field in form %}
        <div {% if field.label|lower == "password" and not gallery.lock and not field.errors %}style="display:none;"{% endif %}class="control-group {{ field.label|lower }} {% if field.errors %}error{% endif %}">
            {{ field.label_tag }}
            <div class="controls">
                {{ field }}
                {{ field.errors }}
            </div>
            {% if field.help_text %}
            <p class="help-block">{{ field.help_text }}</p>
            {% endif %}
        </div>
        {% endfor %}
  </fieldset>
    <input type="submit" class="btn btn-large btn-primary" value="Done" />
</form>
{% if not gallery.published %}
<p>Preview your gallery here</p>
{% else %}
<p>View your gallery live !!!</p>
{% endif %}
<a href="{% url "media-gallery" gallery.collection.slug gallery.slug %}">{{ gallery.name }}</a>
<ul class="thumbnails">
{% for picture in gallery.images.all %}
    <li class=".span3">
    <div class="thumbnail">
        <a href="{% url "gallery-delete-image" gallery.slug picture.pk %}"><i class="icon-trash"></i></a>
        <img src="{{ picture.thumbnail.url }}" width="{{ picture.thumbnail.width }}" height="{{ picture.thumbnail.height }}" />
    </div>
    </li>
{% endfor %}
</ul>
{% endblock %}

{% block js %}
<script type="text/javascript" src="{{ STATIC_URL }}jQuery-Slugify-Plugin/jquery.slugify.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}Impromptu/js/jquery-impromptu.4.0.min.js"></script>
<script src="{{ STATIC_URL }}iphone-style-checkboxes/js/iphone-style-checkboxes.js" type="text/javascript"></script>
<script type="text/javascript"> 
    $(document).ready(function (){ 
        $('#id_published').iphoneStyle({
            onChange: function(elem, value) {
                $.getJSON("{% url "gallery-publish" gallery.slug %}", {publish:value.toString()});
            }
        });
        $('#id_lock').iphoneStyle({
            onChange: function(elem, value) {
                var val = value.toString();
                if (val === 'true'){
                    $(".control-group.password").show("fast");
                }
                else{
                    $(".control-group.password").hide("fast");
                }

            },
            checkedLabel: 'Yes',
            uncheckedLabel: 'No'
        });
    }); 
</script>
<script type="text/javascript">
    $('#id_slug').slugify('#id_name');
    $(".thumbnail a").click(function (event) {
        event.preventDefault();
        var atag = $(this);
        var link = atag.attr("href");
        $.prompt("Do you really want to delete this image ?", {
            buttons: { Yes: 1, No: 0 },
            submit:function(e,v,m,f){
                if(v===0){
                    $.prompt.close();
                }
                else if(v===1){
                    $.getJSON(link, function(data) {
                        if(data===0){
                            html = '<div class="alert alert-error"><button class="close" data-dismiss="alert">×</button>Oops something went wrong, image was not deleted.</div>'
                        }
                        else{
                                html = '<div class="alert alert-success"><button class="close" data-dismiss="alert">×</button>Your image has been deleted successfully.</div>'
                                atag.parent('div').parent('li').remove()
                            }
                        $(html).prependTo($('.container'));
                    });
                    return true;
                }
            }
        });
    });
</script>
{% endblock js %}

media_gallery/templates/media-gallery/upload_images.html
{% extends "media-gallery/base.html" %}

{% block extra-style %}
<link href="//ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css" rel="stylesheet" type="text/css"/>
<link rel="stylesheet" href="{{ STATIC_URL }}plupload/js/jquery.ui.plupload/css/jquery.ui.plupload.css" type="text/css" />
{% endblock extra-style %}

{% block title %}Upload Images{% endblock %}

{% block content %}
<form id="upload-form" action="" method="post" enctype="multipart/form-data">{% csrf_token %}
    <div class="row">
        <div class="span7">
            <span id="add-files" class="btn btn-success fileinput-button">
                <i class="icon-plus icon-white"></i>
                <span>Add files...</span>
            </span>
            <button type="submit" id="form-submit" class="btn btn-primary start">
                <i class="icon-upload icon-white"></i>
                <span>Start upload</span>
            </button>
            <button type="reset" class="btn btn-warning cancel">
                <i class="icon-ban-circle icon-white"></i>
                <span>Cancel upload</span>
            </button>
        </div>
    </div>
    <div id="upload">
        <div id="upload-container2">
            <div id="upload-border">
                <div id="upload-container">
                    <img src="{{ STATIC_URL }}testimage.jpg" width="441" height="369" />
                </div>
            </div>
        </div>
        <div class="progress progress-striped">
            <div class="bar"></div>
        </div>
        <div class="span5 fileupload-progress fade">
            <!-- The global progress bar -->
            <div class="progress progress-success progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
                <div class="bar" style="width:0%;"></div>
            </div>
        </div>
        <table class="table table-striped">
            <tbody id="files">
            </tbody>
        </table>
    </div>
 </form>
{% endblock content %}

{% block js %}
<script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}plupload/js/plupload.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}plupload/js/plupload.html4.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}plupload/js/plupload.html5.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}plupload/js/jquery.ui.plupload/jquery.ui.plupload.js"></script> 
<script type="text/javascript">
$(function() {
    var uploader = new plupload.Uploader({
        // General settings
        runtimes : 'html5, html4',
        url : '{% url "uploadit-upload-image" %}',
        max_file_size : '1000mb',
        max_file_count: 100,
        browse_button: 'add-files',
        drop_element: 'upload-container',
        // Disabled due to a bug that loses the original image name and creates blobs.
        //chunk_size : '1mb',
        container : 'upload',
        unique_names : false,
        multiple_queues : true,
        // Specify what files to browse for
        filters : [
            {title : "Image files", extensions : "jpg,png,jpeg"},
        ],

        multipart_params: {gallery: "{{ gallery.pk }}"}
    });

    uploader.init();

    $('#form-submit').click(function(e) {
        // Don't submit the form yet :)
        e.preventDefault();
        if(uploader.total.queued != 0) {
            uploader.start();
        }
        
    });

    uploader.bind('FilesAdded', function(up, files) {
        $.each(files, function(i, file) {
            $('#files').append(
                '<tr id="'+file.id+'"><td>'+file.name+'</td>'+
                '<td>'+plupload.formatSize(file.size)+'</td>'+
                '<td class="cancel-' + file.id +'"><button class="btn btn-warning"><i class="icon-ban-circle icon-white"></i>Cancel</button></td></tr>'
            );
            $('.cancel-' + file.id).click(function(e) {
                e.preventDefault();
                uploader.removeFile(file);
                $('#' + file.id).remove();
            });
        });
    });

    uploader.bind('UploadProgress', function(up, file) {
        $(".bar").css("width", up.total.percent);
    });

    uploader.bind('UploadComplete', function(up, files){
        $("form:first").submit();
    });

    uploader.bind('Error', function(up, err) {
        $('#filelist').append("<div>Error: " + err.code +
            ", Message: " + err.message +
            (err.file ? ", File: " + err.file.name : "") +
            "</div>"
        );
    });
});
</script>
{% endblock js %}